---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install the webserver on ubuntu 16
    apt:
     name: appache2
     state: present
    when: ansible_os_family =="Debian"

  - name: start the web server on ubuntu 16
    service:
     name: appache2
     state: started
    when: ansible_os_family =="Debian"


  - name: install the webser on RedHat nodes
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"

  - name: start the webserver on RedHat machines
    service:
     name: httpd
     state: started
    when: ansible_os_family =="RedHat"


