---
- hosts: all
  become: yes
  tasks:
  - name: install the git on ubuntu 16
    apt:
      name: git
      state: absent
    when: ansible_os_family =="Debian"
  - name: install the httpd webserver on RedHat
    yum:
      name: httpd 
      state: absent
    when: ansible_os_family =="RedHat"
