---
- hosts: all
  become: yes
  tasks:
  - name: install the webserver on ubuntu 16
    apt:
     name: git
     state: present

  - name: install the webserver on ubuntu 16
    apt:
     name: apache2 
     state: present
